name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to 'master' if your default branch is named master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Inject Secret Token
        run: |
          # Replace placeholder in your file with the actual secret
          # Ensure the path below matches the location of your lang.js
          sed -i 'GH_PAT/${{ secrets.GH_PAT }}/g' js/lang.js

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.' # This uploads your entire folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
